# Generated by Django 6.0.6 on 2026-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='ppts',
            field=models.BooleanField(default=False),
        ),
    ]
