# Generated by Django 6.0.6 on 2026-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_inquiry_ppts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
